language: c
sudo: required
dist: trusty
service:
- docker
install:
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/
  trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177 lftp
- nvm use 4.1.2
- npm install -g bower
- npm install -g gulp
script:
- dotnet restore
- dotnet build
- dotnet publish -o output
- docker build -t bis0n/aspnet-linux:latest .
- sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- sudo docker push bis0n/aspnet-linux:latest
DOCKER_USERNAME=bis0n:
  secure: XzdYd+g4eWyEO6zLYJ0zs1rfG/0bKf0MkGHvvBurs6aLf3SwT7+TiSbf9GudSyRsuTJb89SIuXXkUh9CmpGFwp9xkBQ24HAkhdDwFgqRWk0ba7jUgrO/38EHo5fjIRvRtjZuQA5KoQjnwj35vu68p+o2H7wgrvyU7zmJo3BRlhsLK5yaFEuFSG5zzGgY21w/qefTNOapxwFfRoXNoyh3LEiZsKq1wmAvZwL252St06rLQ1vDqCRpWezgT7UEC8KWuO+N/dDr0OFCQoCvzBCUeq4CVPL19qwMH/W9Uv14OU7SATGXGNfc1OPs7UmaRCIUE+adbDsh/C7VcRnkm79xGIpLbFskFAvXV2ARkI6Bo7H6teoqiTDAoVmPMJsrLAWhfmB/Qz8ruxm30mOhpP/y8glBjEdkF5JcpnkbIoNtkxSV5BqcgYMnLS/AtQB26ezNeanJ2TAk9hRydqOlLY65Qo2K8CdeiTkLRbljmywOAW55sNKc7PsjmpWCCrlYALy1ojysLFps6tn5wOKgs7uPXLf4RJKpFjKZUN9gw/NcpJPZDT0LFEapVaoGtbzlvi3j5NTtJid+hBRrENba93mEHpJas1f3hEHbC1M4JKpXjI9TSOyErYSYvZq9pKRv4rzDUULW/gL/BtemCBacCzUjNu/FFa7Hz5GbX9Obxy95Kf4=
