language: csharp
sudo: required
dist: trusty
install:
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/
  trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
- env GIT_SSH=$PWD/.ssh/ssh.sh git clone git@github.com:x2048/aspnet-linux-deployment.git output
- nvm use 4.1.2
- npm install -g bower
- npm install -g gulp
script:
- dotnet restore
- dotnet build
- dotnet publish -o output
- cd output
- git add --force .
- git commit -m "Build"
- env GIT_SSH=$PWD/../.ssh/ssh.sh git push origin +master:master
before_install:
- openssl aes-256-cbc -K $encrypted_bdf4b4e1025f_key -iv $encrypted_bdf4b4e1025f_iv
  -in id_rsa.enc -out .ssh/id_rsa -d
