language: c
sudo: required
dist: trusty
service:
- docker
install:
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/
  trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177 lftp
- nvm use 4.1.2
- npm install -g bower
- npm install -g gulp
script:
- dotnet restore
- dotnet build
- dotnet publish -o output
- docker build aspnet-linux
